services:
  - type: web
    name: taskrabbit
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskrabbit-db
          property: connectionString

databases:
  - name: taskrabbit-db
    databaseName: taskrabbit
    user: taskrabbit
    plan: free 